"""drop sections table

Revision ID: d129f49fece7
Revises: 08717921e0e1
Create Date: 2026-08-10 21:17:15.415473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd129f49fece7'
down_revision: Union[str, None] = '08717921e0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sections_id', table_name='sections')
    op.drop_index('ix_sections_parent_id', table_name='sections')
    op.drop_index('ix_sections_slug', table_name='sections')
    op.drop_table('sections')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_visible', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['sections.id'], name='sections_parent_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='sections_pkey'),
    sa.UniqueConstraint('slug', name='sections_slug_key')
    )
    op.create_index('ix_sections_slug', 'sections', ['slug'], unique=True)
    op.create_index('ix_sections_parent_id', 'sections', ['parent_id'], unique=False)
    op.create_index('ix_sections_id', 'sections', ['id'], unique=False)
    # ### end Alembic commands ###
