"""Add cloudinary metadata to sidebar_items and contact_links

Revision ID: 6e7110f77a85
Revises: bbbbbbb22222
Create Date: 2026-08-13 01:26:27.880827

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6e7110f77a85'
down_revision: str | None = 'bbbbbbb22222'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_links', sa.Column('icon_url', sa.String(), nullable=True))
    op.add_column('contact_links', sa.Column('icon_public_id', sa.String(), nullable=True))
    op.add_column('sidebar_items', sa.Column('icon_url', sa.String(), nullable=True))
    op.add_column('sidebar_items', sa.Column('icon_public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sidebar_items', 'icon_public_id')
    op.drop_column('sidebar_items', 'icon_url')
    op.drop_column('contact_links', 'icon_public_id')
    op.drop_column('contact_links', 'icon_url')
    # ### end Alembic commands ###
