"""refactor_skills_to_use_domains_and_levels

Revision ID: 214b77715645
Revises: 2db414b07b99
Create Date: 2026-08-13 22:51:27.686916

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "214b77715645"
down_revision: str | None = "2db414b07b99"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 1. Add 'level' column with a default
    op.add_column(
        "skills",
        sa.Column(
            "level", sa.String(length=50), server_default="Working", nullable=False
        ),
    )

    # 2. Map canonical skills to their appropriate qualitative level (Core, Hands-on, Working)
    # The default is already "Working", so we only need to map "Core" and "Hands-on".
    op.execute("""
        UPDATE skills
        SET level = 'Core'
        WHERE name IN (
            'Python', 'Flask', 'FastAPI', 'REST API Design', 'SQLAlchemy',
            'JWT Authentication', 'PostgreSQL', 'Database Design',
            'Schema Design & Normalization', 'Pytest', 'API Testing',
            'Git & GitHub', 'Technical Documentation'
        )
    """)

    op.execute("""
        UPDATE skills
        SET level = 'Hands-on'
        WHERE name IN (
            'Rate Limiting', 'Background Jobs / APScheduler', 'SQLite',
            'HTML', 'CSS', 'JavaScript', 'Responsive UI',
            'GitHub Actions / CI', 'Render', 'Railway',
            'API Integration', 'Code Auditing & Remediation'
        )
    """)

    # 3. We also need to map the legacy 'category' string to 'domain_id' if they are missing
    # Let's ensure domains exist
    op.execute("""
        INSERT INTO skill_domains (name, sort_order)
        SELECT DISTINCT category, 0 FROM skills WHERE category IS NOT NULL
        ON CONFLICT DO NOTHING
    """)

    # Link domains
    op.execute("""
        UPDATE skills s
        SET domain_id = d.id
        FROM skill_domains d
        WHERE s.category = d.name AND s.domain_id IS NULL
    """)

    # 4. Drop the legacy columns
    op.drop_column("skills", "category")
    op.drop_column("skills", "proficiency")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "skills",
        sa.Column(
            "proficiency",
            sa.INTEGER(),
            server_default="0",
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "skills",
        sa.Column(
            "category", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )

    # Attempt to restore some basic data (lossy)
    op.execute("""
        UPDATE skills s
        SET category = d.name,
            proficiency = CASE
                WHEN level = 'Core' THEN 100
                WHEN level = 'Hands-on' THEN 80
                ELSE 60
            END
        FROM skill_domains d
        WHERE s.domain_id = d.id
    """)

    op.drop_column("skills", "level")
    # ### end Alembic commands ###
