"""add project subtitle

Revision ID: 2db414b07b99
Revises: 6e7110f77a85
Create Date: 2026-08-13 21:06:05.721076

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2db414b07b99'
down_revision: str | None = '6e7110f77a85'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('subtitle', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'subtitle')
    # ### end Alembic commands ###
