"""Add resume_file model

Revision ID: 08717921e0e1
Revises: d00cdc66c994
Create Date: 2026-08-10 20:57:24.529381

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
"""Add resume_file model

Revision ID: 08717921e0e1
Revises: d00cdc66c994
Create Date: 2026-08-10 20:57:24.529381

"""


# revision identifiers, used by Alembic.
revision: str = '08717921e0e1'
down_revision: str | None = 'd00cdc66c994'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_file_id'), 'resume_file', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_file_id'), table_name='resume_file')
    op.drop_table('resume_file')
    # ### end Alembic commands ###
