"""Add SidebarItem model

Revision ID: 19ec71035ea7
Revises: d129f49fece7
Create Date: 2026-08-11 16:47:06.933760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19ec71035ea7'
down_revision: Union[str, None] = 'd129f49fece7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sidebar_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=True),
    sa.Column('icon_data', sa.LargeBinary(), nullable=True),
    sa.Column('icon_mime', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sidebar_items_id'), 'sidebar_items', ['id'], unique=False)
    op.create_index(op.f('ix_sidebar_items_slug'), 'sidebar_items', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sidebar_items_slug'), table_name='sidebar_items')
    op.drop_index(op.f('ix_sidebar_items_id'), table_name='sidebar_items')
    op.drop_table('sidebar_items')
    # ### end Alembic commands ###
