"""add_about_closing_fields

Revision ID: 96995a85652a
Revises: 19ec71035ea7
Create Date: 2026-08-11 23:02:19.561079

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '96995a85652a'
down_revision: str | None = '19ec71035ea7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about_config', sa.Column('closing_title', sa.String(length=255), nullable=True))
    op.add_column('about_config', sa.Column('closing_text', sa.Text(), nullable=True))
    op.alter_column('projects', 'tech_stack',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('projects', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('projects', 'tech_stack_legacy')
    op.alter_column('skills', 'proficiency',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('skills', 'proficiency_legacy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('proficiency_legacy', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.alter_column('skills', 'proficiency',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.add_column('projects', sa.Column('tech_stack_legacy', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False))
    op.alter_column('projects', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('projects', 'tech_stack',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    op.drop_column('about_config', 'closing_text')
    op.drop_column('about_config', 'closing_title')
    # ### end Alembic commands ###
