"""phase_3_cms_models

Revision ID: 394a27052a8a
Revises: 2e71187d4cd4
Create Date: 2026-08-09 19:31:26.463955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '394a27052a8a'
down_revision: Union[str, None] = '2e71187d4cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('top_text', sa.String(length=255), nullable=True),
    sa.Column('big_text', sa.Text(), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('current_focus', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('currently_learning', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_about_config_id'), 'about_config', ['id'], unique=False)
    op.create_table('contact_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('top_text', sa.String(length=255), nullable=True),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_config_id'), 'contact_config', ['id'], unique=False)
    op.create_table('contact_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_links_id'), 'contact_links', ['id'], unique=False)
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_id'), 'education', ['id'], unique=False)
    op.create_table('home_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('top_text', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('intro', sa.Text(), nullable=True),
    sa.Column('roles', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('social_links', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('action_projects_label', sa.String(length=255), nullable=True),
    sa.Column('action_about_label', sa.String(length=255), nullable=True),
    sa.Column('action_contact_label', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_config_id'), 'home_config', ['id'], unique=False)
    op.create_table('projects_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('top_text', sa.String(length=255), nullable=True),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_config_id'), 'projects_config', ['id'], unique=False)
    op.create_table('public_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tech_stack_text', sa.Text(), nullable=True),
    sa.Column('author_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_settings_id'), 'public_settings', ['id'], unique=False)
    op.create_table('resume_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('top_text', sa.String(length=255), nullable=True),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_config_id'), 'resume_config', ['id'], unique=False)
    op.create_table('skill_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_domains_id'), 'skill_domains', ['id'], unique=False)
    op.create_table('skills_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('top_text', sa.String(length=255), nullable=True),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_config_id'), 'skills_config', ['id'], unique=False)
    op.add_column('messages', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('featured', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    
    # Safe migration for Project.tech_stack
    op.alter_column('projects', 'tech_stack', new_column_name='tech_stack_legacy')
    op.add_column('projects', sa.Column('tech_stack', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default='[]'))
    
    op.add_column('skills', sa.Column('domain_id', sa.Integer(), nullable=True))
    op.add_column('skills', sa.Column('icon', sa.String(length=255), nullable=True))
    
    # Safe migration for Skill.proficiency
    op.alter_column('skills', 'proficiency', new_column_name='proficiency_legacy')
    op.add_column('skills', sa.Column('proficiency', sa.Integer(), nullable=False, server_default=sa.text('0')))
    
    op.alter_column('skills', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    
    # Naming the constraint is better for SQLite compatibility during migrations
    op.create_foreign_key('fk_skills_domain_id', 'skills', 'skill_domains', ['domain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_skills_domain_id', 'skills', type_='foreignkey')
    op.alter_column('skills', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    
    op.drop_column('skills', 'proficiency')
    op.alter_column('skills', 'proficiency_legacy', new_column_name='proficiency')
    
    op.drop_column('skills', 'icon')
    op.drop_column('skills', 'domain_id')
    
    op.drop_column('projects', 'tech_stack')
    op.alter_column('projects', 'tech_stack_legacy', new_column_name='tech_stack')
    
    op.drop_column('projects', 'featured')
    op.drop_column('messages', 'phone')
    op.drop_index(op.f('ix_skills_config_id'), table_name='skills_config')
    op.drop_table('skills_config')
    op.drop_index(op.f('ix_skill_domains_id'), table_name='skill_domains')
    op.drop_table('skill_domains')
    op.drop_index(op.f('ix_resume_config_id'), table_name='resume_config')
    op.drop_table('resume_config')
    op.drop_index(op.f('ix_public_settings_id'), table_name='public_settings')
    op.drop_table('public_settings')
    op.drop_index(op.f('ix_projects_config_id'), table_name='projects_config')
    op.drop_table('projects_config')
    op.drop_index(op.f('ix_home_config_id'), table_name='home_config')
    op.drop_table('home_config')
    op.drop_index(op.f('ix_education_id'), table_name='education')
    op.drop_table('education')
    op.drop_index(op.f('ix_contact_links_id'), table_name='contact_links')
    op.drop_table('contact_links')
    op.drop_index(op.f('ix_contact_config_id'), table_name='contact_config')
    op.drop_table('contact_config')
    op.drop_index(op.f('ix_about_config_id'), table_name='about_config')
    op.drop_table('about_config')
    # ### end Alembic commands ###
