"""Add ReadmeConfig and CertificatesConfig

Revision ID: d00cdc66c994
Revises: 394a27052a8a
Create Date: 2026-08-10 20:33:25.295523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd00cdc66c994'
down_revision: Union[str, None] = '394a27052a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_config_id'), 'certificates_config', ['id'], unique=False)
    op.create_table('readme_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readme_config_id'), 'readme_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readme_config_id'), table_name='readme_config')
    op.drop_table('readme_config')
    op.drop_index(op.f('ix_certificates_config_id'), table_name='certificates_config')
    op.drop_table('certificates_config')
    # ### end Alembic commands ###
